# Generated by Django 5.1.7 on 2025-03-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoapp', '0003_alter_contactmessage_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(default='https://facebook.com/')),
                ('tiktok', models.URLField(default='https://tiktok.com/')),
                ('linkedin', models.URLField(default='https://linkedin.com/')),
            ],
        ),
    ]
