# Generated by Django 5.1.7 on 2025-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocoapp', '0004_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Səbail rayonu, H.Z.Tağıyev 10 (Fəvvarələr Meydanı)', max_length=255)),
                ('contact_email', models.EmailField(default='chocolux@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(default='+994 51 651 09 09', max_length=20)),
            ],
        ),
    ]
